### ISSUE TITLE
Texture around exhaust

### ISSUE THREAD

**Issue by LeroyTFR** [VurtualRuler98/vurtual_mtvr#1]
Hello,
I am informing you about "ghost" texture around exhaust. All MTVR trucks have it.  Thank you for information about progress.
![desktop screenshot 2018 06 02 - 11 43 35 95](https://user-images.githubusercontent.com/44523369/47603554-b14ead00-d9ed-11e8-8b88-e80f9f600e9e.png)
![desktop screenshot 2018 06 02 - 11 43 48 40](https://user-images.githubusercontent.com/44523369/47603555-b14ead00-d9ed-11e8-870d-c49c9e6d4423.png)
![desktop screenshot 2018 06 02 - 11 44 00 19](https://user-images.githubusercontent.com/44523369/47603556-b1e74380-d9ed-11e8-917d-b1698f6d8aec.png)
![desktop screenshot 2018 06 02 - 11 44 08 92](https://user-images.githubusercontent.com/44523369/47603557-b1e74380-d9ed-11e8-9e10-c9817f24be46.png)

**Comment by VurtualRuler98** [comment]
Fixed in the next release.
